# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: 'npm install' 
      - run:
          name: Install snyk
          command: 'npm install snyk'
      - snyk/scan:
         fail-on-issues: false
         monitor-on-build: true    
      - snyk/scan:
          docker-image-name: shannreid/juice-shop
          target-file: "Dockerfile"
          fail-on-issues: false                                # create a snapshot of apps dependencies on snyk.io, for continoues monitoring (recommended!)
      - run:
          name: snyk code test
          command: 'snyk code test'
workflows:
  test:
    jobs:
      - snyk/scan-iac