# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: 'npm install' 
      - run:
          name: Install snyk
          command: 'npm install snyk'
      - run: 
          name: build docker image
          command: 'docker build - t juice-shop:latest .'
      - run:
          command: 'snyk container test shannreid/juice-shop:latest' 
                              # create a snapshot of apps dependencies on snyk.io, for continoues monitoring (recommended!)
workflows:
  test:
    jobs:
      - build
      - snyk/scan-iac