# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2
jobs:
  snyktest:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: 'npm install' 
      - snyk/scan:
          fail-on-issues: false
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            export TAG=latest
            export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME
            docker build -t shannreid/juice-shop -t shannreid/juice-shop:latest .
      - snyk/scan:
          docker-image-name: shannreid/juice-shop
          target-file: "Dockerfile"
          fail-on-issues: true 
  snykcode:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: snyk code
          command: 'snyk code test'                    # create a snapshot of apps dependencies on snyk.io, for continoues monitoring (recommended!)
workflows:
  test:
    jobs:
      - snyktest
      - build_docker_image
      - snyk/scan-iac