# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs: 
  snyk: snyk/snyk@1.1.2
  circleci: circleci/python@2.1.1
jobs:
  snyk-to-html:
    docker:
      - image: cimg/node:12.13.1
      - image: cimg/python:3.10.7-node
    steps:
      - checkout
      - run:
          name: snyk to html
          command: |            
            npm install --location=global snyk
            npm install --location=global snyk-to-html
            snyk test --json | snyk-to-html -o results.html
      - store_artifacts:
            path: /project/html
  snyk-test:
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Install npm dependencies
          command: |
            npm install
      - snyk/scan:
          command: test
          fail-on-issues: false
          monitor-on-build: false
          severity-threshold: medium
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            export TAG=latest
            export IMAGE_NAME=$CIRCLE_PROJECT_REPONAME
            docker build -t shannreid/juice-shop -t shannreid/juice-shop:latest .
      - snyk/scan:
          docker-image-name: shannreid/juice-shop
          target-file: "Dockerfile"
          fail-on-issues: true  
  snykcode:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - snyk/scan:
          fail-on-issues: true 
          additional-arguments: '--code'                # create a snapshot of apps dependencies on snyk.io, for continoues monitoring (recommended!)
workflows:
  test:
    jobs:
      - snyk-to-html
      - snyk-test
      - snykcode
      - snyk/scan-iac
      - build_docker_image