
name: Snyk Container Scan + API Call
on: [push, pull_request]
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build a Docker image
      run: docker build -t docker-goof .
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: docker-goof
        args: --file=Dockerfile
        
    - name: API Call
      run: |
        cd bash-script
        sh cr_import.sh
