name: Snyk Test
on: pull_request
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
    - name: install snyk to html
      run: sudo npm install snyk-to-html -g
    - name: output to HTML
      run: | 
        snyk test --sarif > results.sarif
    - name: upload sarif file
      uses: github/codeql-action/upload-sarif@v1
      with: 
        sarif_file: results.sarif
    - name: archive snyk results
      uses: actions/upload-artifact@v2
      with:
        name: archive snyk results
        path: results.sarif
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
       
